name: Upload a Build Artifacts
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  win64-native-shared:
    name: 'x64 (MSVC): Windows (VS 2022, shared)'
    # See: https://github.com/actions/runner-images#available-images.
    runs-on: windows-2022
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate buildsystem
        run: cmake -E env CFLAGS="/WX" cmake -B build -DSECP256K1_ENABLE_MODULE_RECOVERY=ON -DSECP256K1_BUILD_EXAMPLES=ON -A x64 -DBUILD_SHARED_LIBS=ON

      - name: Build
        run: cmake --build build --config RelWithDebInfo -- /p:UseMultiToolTask=true /maxCpuCount

      - name: Binaries info
        # Use the bash shell included with Git for Windows.
        shell: bash
        run: |
          cd build/bin/RelWithDebInfo && file *tests.exe bench*.exe libsecp256k1-*.dll || true

      - name: Check
        run: |
          ctest -C RelWithDebInfo --test-dir build -j ([int]$env:NUMBER_OF_PROCESSORS + 1)
          build\bin\RelWithDebInfo\bench_ecmult.exe
          build\bin\RelWithDebInfo\bench_internal.exe
          build\bin\RelWithDebInfo\bench.exe

      - name: Create archive
        run: 7z a build-win64-shared.zip build\bin\RelWithDebInfo\libsecp256k1-*.dll

      - name: Upload Release
        uses: actions/upload-artifact@v4.4.3
        with:
          path: build-win64-shared.zip
